/* ==================================================================
   Piezas de ejemplo · se muestran mientras no conectes tu hoja de
   Google (config.js → urlScript). Las imágenes son dibujos generados
   por código ("dibujo:objeto/patrón"), así que no pesan nada.
   ================================================================== */
window.INLUNA_DEMO = {
  ajustes: {},
  productos: [
    { id: 'taza-seigaiha', nombre: 'Taza Seigaiha', precio: 320, categoria: 'Cerámica', estado: 'disponible', destacado: true, orden: 1,
      descripcion: 'Taza de cerámica pintada a mano con escamas de olas.\nApta para microondas.',
      medidas: '9 cm de alto · 350 ml', entrega: '2 a 3 días', colores: 'Azul, Verde, Café',
      fotos: ['dibujo:taza/escamas', 'dibujo:taza/puntos', 'dibujo:taza/olas'] },
    { id: 'plato-mar-de-noche', nombre: 'Plato Mar de noche', precio: 450, categoria: 'Cerámica', estado: 'disponible', orden: 2,
      descripcion: 'Plato con borde de olas y un destello al centro.', medidas: '24 cm de diámetro',
      fotos: ['dibujo:plato/olas', 'dibujo:plato/escamas'] },
    { id: 'jarron-ramitas', nombre: 'Jarrón Ramitas', precio: 680, categoria: 'Cerámica', estado: 'encargo', orden: 3,
      descripcion: 'Jarrón con ramitas pintadas una por una.', medidas: '22 cm de alto', entrega: '2 a 3 semanas', materiales: 'Barro, Porcelana',
      fotos: ['dibujo:jarron/ramitas', 'dibujo:jarron/flores'] },
    { id: 'azulejo-destellos', nombre: 'Azulejo Destellos', precio: 180, categoria: 'Cerámica', estado: 'disponible', orden: 4,
      descripcion: 'Azulejo decorativo con gancho para colgar.', medidas: '15 × 15 cm',
      fotos: ['dibujo:azulejo/destellos', 'dibujo:azulejo/rombos'] },
    { id: 'libreta-arcos', nombre: 'Libreta Arcos', precio: 220, categoria: 'Papelería', estado: 'disponible', destacado: true, orden: 5,
      descripcion: 'Libreta con espiral y hojas punteadas.', medidas: 'A5 · 80 hojas',
      fotos: ['dibujo:libreta/arcoiris'] },
    { id: 'libreta-tejido', nombre: 'Libreta Tejido', precio: 220, categoria: 'Papelería', estado: 'agotado', orden: 6,
      descripcion: 'Libreta A5 con espiral y 80 hojas lisas.',
      fotos: ['dibujo:libreta/tejido'] },
    { id: 'lamina-cielo', nombre: 'Lámina Cielo', precio: 350, categoria: 'Láminas', estado: 'disponible', orden: 7,
      descripcion: 'Impresión en papel de algodón, firmada a mano.', medidas: 'Tamaño carta',
      fotos: ['dibujo:lamina/estrellas'] },
    { id: 'lamina-jardin', nombre: 'Lámina Jardín', precio: 350, categoria: 'Láminas', estado: 'disponible', destacado: true, orden: 8,
      descripcion: 'Impresión en papel de algodón, firmada a mano.', medidas: 'Tamaño carta',
      fotos: ['dibujo:lamina/flores'] },
    { id: 'lamina-oleaje', nombre: 'Lámina Oleaje', precio: 350, categoria: 'Láminas', estado: 'disponible', orden: 9,
      descripcion: 'Impresión en papel de algodón, firmada a mano.', medidas: 'Tamaño carta',
      fotos: ['dibujo:lamina/olas'] },
    { id: 'bolsa-ajedrez', nombre: 'Bolsa Ajedrez', precio: 390, categoria: 'Textil', estado: 'disponible', orden: 10,
      descripcion: 'Tote bag estampada a mano con tinta textil.', medidas: '38 × 42 cm', colores: 'Natural, Negro', materiales: 'Manta, Lona',
      fotos: ['dibujo:bolsa/ajedrez'] },
    { id: 'playera-destellos', nombre: 'Playera Destellos', precio: 280, categoria: 'Textil', estado: 'disponible', orden: 11,
      descripcion: 'Playera de algodón estampada con serigrafía.', entrega: '5 días', tallas: 'CH, M, G, EG', colores: 'Blanco, Negro',
      fotos: ['dibujo:bolsa/gotas'] },
    { id: 'llaveros-personalizados', nombre: 'Llaveros personalizados', precio: 'Desde $25', categoria: 'Textil', estado: 'encargo', orden: 12,
      descripcion: 'Con el nombre o el diseño que quieras.', entrega: '1 a 2 semanas', minimo: 10, materiales: 'Madera, Acrílico',
      fotos: ['dibujo:azulejo/destellos'] },
  ],
};
